### ISSUE TITLE
script t.b.v. demo data

### ISSUE THREAD

**Issue by mathemaat** [jonge-democraten/zues#10]
Het zou fijn zijn als er net als bij de website een script wordt meegeleverd dat demo data genereert.

Aandachtspunten:

* Toevoegen van één of meerdere leden (incl. uitleg over hoe in te loggen om "eigen" moties te bekijken)
* Verschillende soorten moties en stukken beschikbaar
* Settings definiëren, zodat het systeem open staat voor nieuwe moties en stukken.

**Comment by trolando** [comment]
Misschien is het ook handig om een paar "developer tools" toe te voegen, zoals "MAAK ALLES OPEN".
Ik word helemaal gek van elke keer dat ik iets test handmatig al die deadlines in te stellen.

**Comment by mathemaat** [comment]
Jouw suggestie heb ik opgelost door in de demo data een einddatum op te nemen van 31 december 2029 voor alle categorieën. Als je daarmee niet tevreden bent, dan kun je het beste een nieuw issue aanmaken.
